cmake_minimum_required(VERSION 3.16)

project(lineCounter LANGUAGES CXX VERSION 0.0.1)

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Core)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Core)

add_executable(lineCounter
  main.cpp
)
target_link_libraries(lineCounter Qt${QT_VERSION_MAJOR}::Core)

include(GNUInstallDirs)
install(TARGETS lineCounter
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)

set_property (SOURCE main.cpp PROPERTY COMPILE_DEFINITIONS VERSION="${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}")


#cpack stuff
include(InstallRequiredSystemLibraries)

#set (CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set (CPACK_PACKAGE_DESCRIPTION_SUMMARY "${PROJECT_NAME} - code line counter (C/C++)")
set (CPACK_PACKAGE_VENDOR "David Netherwood")
set (CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set (CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set (CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")
set (CPACK_PACKAGE_CONTACT "david_netherwood@hotmail.com")
set (CPACK_GENERATOR "DEB")
set (CPACK_DEBIAN_PACKAGE_DEPENDS "libqt6core6")
set (CPACK_PACKAGE_FILE_NAME ${PROJECT_NAME})

include(CPack)
